apiVersion: apps/v1
kind: Deployment
metadata:
  name: mxnet-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mxnet-operator
  template:
    metadata:
      labels:
        app: mxnet-operator
    spec:
      containers:
      - name: mxnet-operator
        image: lever-dev.cargo.io/release/mxnet-operator:v1.0.0-10-gaafca75
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 200Mi
